version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: js-yaml
    versions:
    - 3.14.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
